name: fugoku
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # https://pub.dev/packages/persistent_bottom_nav_bar
  persistent_bottom_nav_bar: ^5.0.2
  # https://pub.dev/packages/flutter_sound_lite
  flutter_sound_lite: ^8.5.0
  # https://pub.dev/packages/permission_handler
  permission_handler: ^10.2.0  
  # https://pub.dev/packages/just_audio
  just_audio: ^0.9.34
  # https://pub.dev/packages/just_audio_background
  just_audio_background: ^0.0.1-beta.10
  # https://pub.dev/packages/audio_video_progress_bar
  audio_video_progress_bar: ^1.0.1
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3
  # https://pub.dev/packages/rxdart
  rxdart: ^0.27.7
  # https://pub.dev/packages/bloc
  bloc: ^8.1.2
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
    # - images/a_dot_ham.jpeg

